[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION  = "10"
  # If you still see peer-dep install issues, temporarily enable:
  # NPM_FLAGS = "--legacy-peer-deps"
