[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# (Optional) relax peer deps if a third-party package complains during install
# [build.environment]
#   NPM_FLAGS = "--legacy-peer-deps"
