# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION  = "10"
  # This key is intentionally public and appears in the client bundle.
  # Allow it so the build doesn't fail.
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"

  # (optional) If you still get hits, you can also omit webpack cache paths:
  # SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/.next/**"
  # (last resort only) Disable scanning entirely:
  # SECRETS_SCAN_ENABLED = "false"
